git-debimport freetds_0.91-2+deb7u1.diff.gz

diff --git a/src/apps/osql b/src/apps/osql
--- a/src/apps/osql
+++ b/src/apps/osql
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $Id: osql,v 1.6 2007/02/06 02:51:18 jklowden Exp $
+# $Id: osql,v 1.11.2.1 2011/05/11 03:10:33 jklowden Exp $
 #
 # Check odbc.ini, odbcinst, and, optionally, freetds.conf, 
 # then execute isql (assume it's unixODBC's isql).  
@@ -41,64 +41,82 @@ fi
 
 # Establish ODBC prefix directory
 
-ODBC_DIR=$(strings ${ISQL} | grep ^/ | grep -v elf | grep -v '\.so\.' | head -1 | sed 's/lib$/etc/' )
+ISQL_DIR=$(strings ${ISQL} | grep ^/ | grep -v elf | grep -v '\.so\.' | head -1 | sed 's/lib$/etc/' )
 
-# N.B.  better than head(1) would be a loop to test the strings.  Since we're looking for a directory, 
-# something like this might work:
-# for D in $(strings ${ISQL} | grep ^/ | grep -v elf | sed 's/lib$/etc/' )
-# do
-# 	if [ -d $D ]
-# 	then
-# 		ODBC_DIR = $D
-# 	fi
-# done
+INI_DIRNAME="/tmp/$(basename $0).$$"
+exec 3> ${INI_DIRNAME}
 
-if [ -z "${ODBC_DIR}" ]
+# Check the libraries, too. 
+if [ -z "${OVER_DIR}" ]
+then 
+	echo "checking shared odbc libraries linked to isql for default directories..."
+	(echo ${ISQL_DIR}; ldd "${ISQL}" | awk '/libodbc\./ {print $3}') \
+	| while read L
+	  do 
+	  	strings "$L" | grep '^/' | grep -v '/lib' \
+		| while read D 
+		  do 
+		  	if [ ! -s "${INI_DIRNAME}" ]
+			then
+			  	printf "	trying $D ... "
+			  	if [ -d "$D" -a -r "${D}/odbc.ini" ]
+				then
+					printf $D >&3
+					printf "OK"
+				else
+					printf "no"
+				fi
+				printf "\n"
+			fi
+		  done
+	  done
+fi
+
+ODBC_DIR=$(cat ${INI_DIRNAME}) && rm ${INI_DIRNAME}
+
+if [ -z "${ODBC_DIR}" -a -z "${OVER_DIR}" ]
 then
-	echo "$(basename $0): error: no potential directory strings in \"$(command -v isql)\""
+	echo "$(basename $0): problem: no potential directory strings in \"$(command -v isql)\""
+	echo "$(basename $0): advice: use \"osql -I DIR\" where DIR unixODBC\'s install prefix e.g. /usr/local"
 	echo "isql strings are:"
 	strings ${ISQL} | grep ^/ | sed 's/^/+ /'
-	exit 1
+	#xit 1
 fi
 
 if [ "${OVER_DIR}" ]
 then
 	if [ -d "${ODBC_DIR}" ]
 	then
-		echo "\"${ODBC_DIR}\" (from isql) is a directory, "
-		echo "	but is overridden by \"${OVER_DIR}\"."
+		echo "\"${ODBC_DIR}\" is a directory, overridden by"
 	else 
-		echo "${ODBC_DIR} (from isql) is not a directory"
-		echo "	and is overridden by \"${OVER_DIR}\"."
+		echo "\"${ODBC_DIR}\" is NOT a directory, overridden by"
 	fi
+	echo "\"${OVER_DIR}\"."
 	
 	if [ -d "${OVER_DIR}" ]
 	then
 		ODBC_DIR=${OVER_DIR}
 	else
-		echo "$(basename $0): error: \"${OVER_DIR}\" is not a directory (disallowing)"
+		echo "$(basename $0): error: \"${OVER_DIR}\" is not a directory"
+		exit 1
 	fi
 fi
 
-if [ ! -d "${ODBC_DIR}" ]
-then
-	echo "$(basename $0): error: ${ODBC_DIR} (from isql) is not a directory!"
-	echo "isql strings are:"
-	strings ${ISQL} | grep ^/ | grep -v elf | grep -v '\.so\.' | sed 's/^/+ /'
-	return 1
-fi
-
-echo "looking for odbc.ini and odbcinst.ini in ${ODBC_DIR}"
-
 # Look for server entry in odbc.ini 
-
+echo 'checking odbc.ini files'
 for F in "${HOME}/.odbc.ini" "${ODBC_DIR}/odbc.ini"
 do
+	if [ ! -d "$(dirname $F)" ]
+	then
+		echo "warning: $(dirname $F) is not a directory" 
+		continue
+	fi
+	
 	if [ -r "$F" ]
 	then
-		echo '	'reading \"$F\"
+		echo "	reading $F"
 	else
-		echo '	'cannot read \"$F\"
+		echo "	cannot read \"$F\""
 		continue
 	fi
 
@@ -106,11 +124,11 @@ do
 
 	if [ $? -eq 0 ]
 	then
-		echo "[${DSN}]" found in \"$F\"
+		echo "[${DSN}] found in $F"
 		ODBC_INI=$F
 		break
 	else
-		echo "[${DSN}]" not found in \"$F\"
+		echo "[${DSN}] not found in $F"
 	fi
 done
 
@@ -132,7 +150,7 @@ sed -ne "${SED_CMD}" ${ODBC_INI}
 # Find the driver in the servername or default section
 for D in "${DSN}" 'default' 
 do
-	echo "looking for driver for DSN [$D]"
+	echo "looking for driver for DSN [$D] in ${ODBC_INI}"
 	grep "$D" ${ODBC_INI} > /dev/null
 	if [ $? -eq 0 ]
 	then
@@ -141,17 +159,18 @@ do
 				| grep -Ei '^[[:space:]]*driver[[:space:]]*=')
 		if [ -z "${DRIVER_LINE}" ]
 		then
-			echo "no driver mentioned for [$D] in $(basename ${ODBC_INI})"
+			echo "  no driver mentioned for [$D] in $(basename ${ODBC_INI})"
 			continue
 		fi
 
-		DRIVER=$(echo ${DRIVER_LINE} | awk '{print $3}')
+		echo "  found driver line: \"${DRIVER_LINE}\""
+		DRIVER=$(echo ${DRIVER_LINE} | awk -F '=' '{print $2}' | sed 's/[[:space:]][[:space:]]*//g')
 		if [ "${DRIVER}" ]
 		then
-			echo "driver \"${DRIVER}\" found for [$D] in $(basename ${ODBC_INI})"
+			echo "  driver \"${DRIVER}\" found for [$D] in $(basename ${ODBC_INI})"
 			break
 		else
-			echo "driver line incomplete for [$D] in $(basename ${ODBC_INI})"
+			echo "  driver line for [$D] incomplete in $(basename ${ODBC_INI})"
 			continue
 		fi
 	fi
@@ -165,12 +184,12 @@ fi
 
 # get filename of driver
 echo found driver named \"${DRIVER}\"
-if [ ! -r "${DRIVER}" ]
+if [ -d "${DRIVER}" -o ! -x "${DRIVER}" ]
 then
 	# not a filename, look it up
 	DRIVERNAME=${DRIVER}
 	ODBC_INST="${ODBC_DIR}/odbcinst.ini"
-	echo "${DRIVERNAME} is not a readable file"
+	echo "\"${DRIVERNAME}\" is not an executable file"
 	echo "looking for entry named [${DRIVERNAME}] in ${ODBC_INST}"
 
 	grep "${DRIVERNAME}" ${ODBC_INST} > /dev/null
@@ -188,31 +207,32 @@ then
 				| grep -Ei '^[[:space:]]*driver[[:space:]]*=')
 	if [ -z "${DRIVER_LINE}" ]
 	then
-		echo "no driver mentioned for [${DRIVERNAME}] in $(basename ${ODBC_INST})"
+		echo "$(basename $0): no driver mentioned for [${DRIVERNAME}] in $(basename ${ODBC_INST})"
 		exit 1
 	fi
 
+	echo "  found driver line: \"${DRIVER_LINE}\""
 	DRIVER=$(echo ${DRIVER_LINE} | awk '{print $3}')
 	if [ -z "${DRIVER}" ]
 	then
-		echo "driver line incomplete for [${DRIVERNAME}] in $(basename ${ODBC_INST})"
+		echo "$(basename $0): driver line incomplete for [${DRIVERNAME}] in $(basename ${ODBC_INST})"
 		exit 1
 	fi
 
-	echo "driver \"${DRIVER}\" found for [${DRIVERNAME}] in $(basename ${ODBC_INST})"
+	echo "  found driver ${DRIVER} for [${DRIVERNAME}] in $(basename ${ODBC_INST})"
 fi
 
 if [ -z "${DRIVER}" ]
 then
-	echo 'error: sorry, failed sanity check: ${DRIVER} is null' 
+	echo $(basename $0): 'error: sorry, failed sanity check: ${DRIVER} is null' 
 	exit 1
 fi
 
-if [ -r "${DRIVER}" ]
+if [ -x "${DRIVER}" ]
 then
-	echo "${DRIVER} is a readable file"
+	echo "${DRIVER} is an executable file"
 else
-	echo "${DRIVER} is not a readable file"
+	echo "${DRIVER} is not an executable file"
 	echo "$(basename $0): error: no driver found for ${DSN}"
 	exit 1
 fi
@@ -236,9 +256,9 @@ echo ${SERVER_LINE} | grep -i servername >/dev/null
 #
 if [ $? -eq 0 ] # ODBC-Combined
 then
-	TDS_SERVER=$(echo ${SERVER_LINE} | awk '{print $3}')
+	TDS_SERVER=$(echo ${SERVER_LINE} | awk -F '=[[:space:]]*' '{print $2}')
 	echo 'Using ODBC-Combined strategy'
-	echo "FreeTDS servername is \"${TDS_SERVER}\" (from ${ODBC_INI})"
+	echo "DSN [${DSN}] has servername \"${TDS_SERVER}\" (from ${ODBC_INI})"
 	if [ -z "${TDS_SERVER}" ]
 	then
 		exit 1
@@ -255,15 +275,15 @@ then
 	
 	for F in "${HOME}/.freetds.conf" "${FREETDS_DIR}/freetds.conf"
 	do
-		echo "looking for [${TDS_SERVER}] in $F"
 		if [ -r "$F" ]
 		then
-			echo "\"$F\" is a readable file"
+			echo $F is a readable file
 		else
 			echo cannot read \"$F\"
 			continue
 		fi
 
+		echo "looking for [${TDS_SERVER}] in $F"
 		grep "[${TDS_SERVER}]" $F > /dev/null
 
 		if [ $? -eq 0 ]
@@ -271,7 +291,7 @@ then
 			FREETDS_CONF=$F
 			break
 		else
-			echo "[${TDS_SERVER}]" not found in \"$F\"
+			echo "[${TDS_SERVER}]" not found in $F
 		fi
 	done
 	
@@ -301,7 +321,7 @@ then
 else # odbc.ini contains a "server", a DNS host
 	HOST=$(echo ${SERVER_LINE} | awk '{print $3}')
 	echo "\"${ATTRIBUTE}\" found, not using freetds.conf"
-	echo "FreeTDS servername is \"${HOST}\""
+	echo "${ATTRIBUTE} is \"${HOST}\""
 	if [ -z "${HOST}" ]
 	then
 		echo "$(basename $0): no value found for \"${ATTRIBUTE}\" entry in $(basename ${ODBC_INI})"
@@ -309,29 +329,52 @@ else # odbc.ini contains a "server", a DNS host
 	fi
 fi
 
+# If the "host" is an ip address, look up the name, for neatness, e.g. 
+## $ host 10.81.36.39
+## 39.36.81.10.IN-ADDR.ARPA domain name pointer ntc5003.eg.com
+if [ "${HOST}" = "$(echo ${HOST} | sed 's/[^.0-9]*//')" ]
+then 
+	ADDRESS=${HOST}
+	echo 'looking up hostname for ip address' ${ADDRESS}
+	HOST=$(host ${HOST} | awk '/domain/ {print $5}' | sed 's/\.$//')
+	if [ -z "${HOST}" ]
+	then
+		echo "$(basename $0): warning: no DNS hostname found for \"${ADDRESS}\""
+	fi
+fi
+
 # Now we have a DNS hostname for the server in HOST
 
-CMD="host ${HOST}"
-
-OUTPUT=$(${CMD})
-ADDRESS=$(echo ${OUTPUT} | sed 's/..*has address //')
+ADDRESS=$(host ${HOST} | awk '/has address/ {print $4}' | head -1)
 if [ -z "${ADDRESS}" ]
 then
 	echo "$(basename $0): no IP address found for \"${HOST}\""
 	exit 1
 fi
 
-echo ${HOST} has address ${ADDRESS}
+#cho ${HOST} has address ${ADDRESS}
 
 # Report what we know and exec isql 
 
-printf "\n";
-printf "%30s:\t%-30s\n" DSN ${DSN}
-printf "%30s:\t%-30s\n" "Server's hostname" ${HOST}
-printf "%30s:\t%-30s\n" Address ${ADDRESS}
-printf "%30s:\t%-30s\n" Driver ${DRIVER}
-printf "\n";
+printf "\n"
+printf "Configuration looks OK.  Connection details:\n\n"
+printf "%22s:\t%-30s\n"  DSN ${DSN}
+printf "%22s:\t%-30s\n"  odbc.ini "${ODBC_INI}"
+printf "%22s:\t%-30s\n"  Driver ${DRIVER}
+printf "%22s:\t%-30s\n" "Server hostname" ${HOST}
+printf "%22s:\t%-30s\n"  Address ${ADDRESS}
+printf "\n"
 
-echo Attempting connection as ${USERNAME}... 
-exec isql ${DSN} ${USERNAME} ${PASSWORD} -v
+echo Attempting connection as ${USERNAME} ... 
+
+if [ -z "${TDSDUMP}" ]
+then 
+	TDSDUMP_AUTO="/tmp/$(basename $0).dump.$$"
+	export TDSDUMP=${TDSDUMP_AUTO}
+fi
+
+( set -x; isql ${DSN} ${USERNAME} ${PASSWORD} -v ) \
+	|| sed -ne 's/Connecting/FAILED &/p' ${TDSDUMP}
+
+test "${TDSDUMP_AUTO}" && rm -f ${TDSDUMP_AUTO}
 
